name: Build Kernel

on:
  push:
    branches: dev

env:
  KERNEL: https://github.com/arcovery/android_kernel_xiaomi_sm8150
  KERNEL_BRANCH: dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@master
         
       - name: Setup Envoirment
         run: |
            sudo -E apt-get -qq install git fakeroot build-essential ncurses-dev xz-utils libssl-dev bc flex libelf-dev bison    

       - name: Clone Kernel and Proton Clang
         run: |
            git clone $KERNEL --depth=1 -b $KERNEL_BRANCH kernel
            
       - name: Building
         run: |
            cd kernel
            bash build.sh
            
       - uses: actions/upload-artifact@v2
         with:
          name: HydrogenKernel
          path: kernel/*.zip
